#ifndef LIBCA_VERSION

// should be autogenerated at some point

#define LIBCA_MAJOR 0
#define LIBCA_MINOR 1
#define LIBCA_PATCH 0
#define LIBCA_VERSION "0.1.0"

#if !(defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L)
# error libca expects C99 or newer.
#endif

#endif
